trigger:
  branches:
    include:
      - main

pool:
  name: 'azuretei'  # veya kullanmak istediğiniz özel bir VM image

jobs:
- job: BuildAndDeployJob
  displayName: 'Build and Deploy Java Project'
  steps:
    - script: |
        echo "Setting JAVA_HOME"
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        echo "Building the services"
        cd smsProxyWebService
        mvn clean install -Dmaven.test.skip
        echo "Build successful. Preparing to copy CAR file to deployments folder."
        mkdir -p $(Build.ArtifactStagingDirectory)/deployments
        cp ./smsProxyWebServiceCompositeExporter/target/*.car $(Build.ArtifactStagingDirectory)/deployments/.
      displayName: 'Build and Copy CAR File'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifacts'
